# Generated by Django 3.0.9 on 2020-08-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='second_category',
        ),
        migrations.AddField(
            model_name='post',
            name='second_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.SecondCategory'),
        ),
    ]
