# Generated by Django 3.0.9 on 2020-08-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='About',
        ),
    ]
