# Generated by Django 3.0.9 on 2020-08-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200829_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ThirdCategory',
            field=models.ForeignKey(blank=True, help_text='قم باختيار اسم  الموضوع', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.ThirdCategory', verbose_name='الموضوع'),
        ),
    ]
