# Generated by Django 3.0.9 on 2020-08-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_thirdcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ThirdCategory',
            new_name='third_category',
        ),
    ]
