# Generated by Django 3.0.9 on 2020-08-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200830_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fourth_category',
            field=models.ForeignKey(blank=True, help_text='قم باختيار اسم  المرحله الدراسيه', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='blog.FourthCategory', verbose_name='المرحله الدراسيه'),
        ),
    ]
