# Generated by Django 3.0.9 on 2020-08-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_fourth_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fourth_category',
        ),
        migrations.RemoveField(
            model_name='thirdcategory',
            name='category',
        ),
    ]
