# Generated by Django 3.0.9 on 2020-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200831_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scripts',
            options={'verbose_name': 'اضافة رابط للموقع', 'verbose_name_plural': 'اضافة رابط للموقع'},
        ),
        migrations.AlterField(
            model_name='scripts',
            name='script',
            field=models.URLField(help_text='قم باضافة رابط الموقع الذي تريد عرضه اسفل الموقع ', verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='title',
            field=models.CharField(max_length=100, verbose_name='اسم الموقع '),
        ),
    ]
