# Generated by Django 3.0.9 on 2020-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200902_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم الموقع ')),
                ('script', models.URLField(help_text='قم باضافة رابط الموقع الذي تريد عرضه اسفل الموقع ', verbose_name='الرابط')),
            ],
            options={
                'verbose_name': 'اضافة رابط للموقع',
                'verbose_name_plural': 'اضافة رابط للموقع',
            },
        ),
        migrations.AlterModelOptions(
            name='scripts',
            options={'verbose_name': 'اضافة سكربت للموقع', 'verbose_name_plural': 'اضافة سكربت للموقع'},
        ),
        migrations.AlterField(
            model_name='scripts',
            name='script',
            field=models.TextField(help_text='(قم باضافة السكربت الذي تريده هنا مثل(كود تفعيل ادسنس ', verbose_name='السكربت'),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='title',
            field=models.CharField(max_length=100, verbose_name='اسم السكربت '),
        ),
    ]
