# Generated by Django 3.0.9 on 2020-08-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200829_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourthCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='المرحله', help_text='قم بادخال اسم المرحلة الدراسيه', max_length=255, verbose_name='المرحله الدراسيه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يفضل تركه فارغا', null=True, unique=True)),
            ],
            options={
                'verbose_name': 'المرحله الدراسيه',
                'verbose_name_plural': 'المراحل الدراسيه',
            },
        ),
        migrations.AlterModelOptions(
            name='thirdcategory',
            options={'verbose_name': 'الماده', 'verbose_name_plural': 'المواد'},
        ),
        migrations.AlterField(
            model_name='post',
            name='third_category',
            field=models.ForeignKey(blank=True, help_text='قم باختيار اسم  الماده', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.ThirdCategory', verbose_name='الماده '),
        ),
        migrations.AlterField(
            model_name='secondcategory',
            name='title',
            field=models.CharField(default='الفصل', help_text='قم بادخال اسم الفصل الدراسي', max_length=255, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='thirdcategory',
            name='title',
            field=models.CharField(default='الماده', help_text='قم بادخال اسم  الماده', max_length=255, verbose_name='الماده'),
        ),
        migrations.AddField(
            model_name='post',
            name='fourth_category',
            field=models.ForeignKey(blank=True, help_text='قم باختيار اسم  المرحله الدراسيه', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.FourthCategory', verbose_name='المرحله الدراسيه'),
        ),
    ]
