# Generated by Django 3.0.9 on 2020-08-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200830_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fourth_category',
            field=models.ForeignKey(blank=True, help_text='قم باختيار اسم  المرحله الدراسيه', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='blog.FourthCategory', verbose_name='المرحله الدراسيه'),
        ),
        migrations.AddField(
            model_name='thirdcategory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='قم باختيار اسم الصف الدراسي', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Category', verbose_name='الصف الدراسي'),
        ),
    ]
