# Generated by Django 3.0.9 on 2020-08-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200830_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم السكربت ')),
                ('script', models.TextField(help_text='(قم باضافة السكربت الذي تريده هنا مثل(كود تفعيل ادسنس ', verbose_name='السكربت')),
            ],
            options={
                'verbose_name': 'اضافة بانر ',
                'verbose_name_plural': 'اضافة بانر ',
            },
        ),
        migrations.CreateModel(
            name='SlideBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم السكربت ')),
                ('script', models.TextField(help_text='(قم باضافة السكربت الذي تريده هنا مثل(كود تفعيل ادسنس ', verbose_name='السكربت')),
            ],
            options={
                'verbose_name': 'اضافة بانر جانبي',
                'verbose_name_plural': 'اضافة بانر جانبي',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='fourth_category',
        ),
        migrations.RemoveField(
            model_name='thirdcategory',
            name='category',
        ),
    ]
